# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port

development:
  api_key: 81890afe5bc5c8797d944ed4e648f6c5
  secret_key: 6839a9b37332d02a19099b7e1e1ed9db
  canvas_page_name: my-gift
  callback_url: http://likeme.luxcement.ru
  tunnel:
    public_host_username: dekart
    public_host: likeme.luxcement.ru
    public_port: 15150
    local_port: 3000

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

production:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:  
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000